# Generated by Django 2.2.2 on 2020-04-06 22:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0002_auto_20200406_2201'),
    ]

    operations = [
        migrations.AlterField(
            model_name='firerecords',
            name='phone_number',
            field=models.CharField(default='14372185806', max_length=20),
        ),
    ]
