# Generated by Django 2.2.2 on 2020-04-08 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('myapp', '0003_auto_20200406_2223'),
    ]

    operations = [
        migrations.AddField(
            model_name='firerecords',
            name='city',
            field=models.CharField(default='Toronto', max_length=55),
        ),
        migrations.AddField(
            model_name='firerecords',
            name='country',
            field=models.CharField(default='Canada', max_length=55),
        ),
        migrations.AddField(
            model_name='firerecords',
            name='lat',
            field=models.CharField(default='43.6934', max_length=55),
        ),
        migrations.AddField(
            model_name='firerecords',
            name='lon',
            field=models.CharField(default='-79.4857', max_length=55),
        ),
        migrations.AddField(
            model_name='firerecords',
            name='region',
            field=models.CharField(default='Ontario', max_length=255),
        ),
    ]
